# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: complytime-providers

before:
    hooks:
        - go mod tidy
        - go mod vendor

builds:
    - id: openscap
      binary: complyctl-provider-openscap
      main: ./cmd/openscap-provider/
      env:
          - CGO_ENABLED=0
      goos:
          - linux
      ldflags:
          - "-X github.com/complytime/complytime-providers/internal/version.version={{ .Version }}"

    - id: ampel
      binary: complyctl-provider-ampel
      main: ./cmd/ampel-provider/
      env:
          - CGO_ENABLED=0
      goos:
          - linux
      ldflags:
          - "-X github.com/complytime/complytime-providers/internal/version.version={{ .Version }}"

    - id: opa
      binary: complyctl-provider-opa
      main: ./cmd/opa-provider/
      env:
          - CGO_ENABLED=0
      goos:
          - linux
      ldflags:
          - "-X github.com/complytime/complytime-providers/internal/version.version={{ .Version }}"

archives:
    - id: openscap
      ids: [openscap]
      formats: ["tar.gz"]
      name_template: >-
          complyctl-provider-openscap_
          {{- .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
    - id: ampel
      ids: [ampel]
      formats: ["tar.gz"]
      name_template: >-
          complyctl-provider-ampel_
          {{- .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
    - id: opa
      ids: [opa]
      formats: ["tar.gz"]
      name_template: >-
          complyctl-provider-opa_
          {{- .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}

changelog:
    sort: asc
    use: github
    format: "{{ .SHA }}: {{ .Message }} ({{ with .AuthorUsername }}@{{ . }}{{ else }}{{ .AuthorName }}{{ end }})"
    filters:
        exclude:
            - "^docs:"
            - "^test:"
            - Merge pull request
    groups:
        - title: "New Features"
          regexp: '^.*?feat(\(.+\))??!?:.+$'
          order: 100
        - title: "Security Updates"
          regexp: '^.*?sec(\(.+\))??!?:.+$'
          order: 150
        - title: "Bug Fixes"
          regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
          order: 200
        - title: "Dependency Updates"
          regexp: '^.*chore\(deps\):.*$'
          order: 250
        - title: "Infrastructure Updates"
          regexp: '^.*ci(\(.*\))?:.*$'
          order: 300
        - title: "Documentation Updates"
          regexp: '^.*?docs?(\(.+\))??!?:.+$'
          order: 400
        - title: "Other Work"
          order: 9999

sboms:
    - id: archive
      artifacts: archive
    - id: source
      artifacts: source

signs:
    - cmd: cosign
      signature: "${artifact}.sigstore.json"
      args:
          - "sign-blob"
          - "--bundle=${signature}"
          - "${artifact}"
          - "--yes"
      artifacts: checksum
      output: true
